class PmbData {
  static const List<String> suburbs = [
    "All Suburbs",
    "Athlone",
    "Ashburton",
    "Blackridge",
    "Boughton",
    "Cascades",
    "Chase Valley",
    "Clarendon",
    "Cleland",
    "CBD / Central",
    "Eastwood",
    "Edendale",
    "Hayfields",
    "Hilton",
    "Imbali",
    "Lincoln Meade",
    "Montrose",
    "Napierville",
    "Northdale",
    "Pelham",
    "Prestbury",
    "Raisethorpe",
    "Scottsville",
    "Sobantu",
    "Town Bush Valley",
    "Wembley",
    "Woodlands",
  ];

  static const List<String> categories = [
    "All Categories",
    "Home & Trades",
    "Food & Bakeries",
    "Automotive",
    "Health & Beauty",
    "Education & Tutors",
    "Professional Services",
    "Events & Markets",
    "Pets & Vets",
  ];
}